#!/usr/bin/env python3
"""
gen_railway_twilio_env.py
=========================
Generates the exact Twilio env-var block to paste into Railway so the deployed
backend uses the SAME Twilio account as the local `.env` — the account that
owns the WhatsApp number and whose Account Auth Token Twilio uses to sign
inbound webhook signatures.

Why this exists:
  - The deployed Railway backend was found running a DIFFERENT Twilio account
    (an `SK…` API Key SID) than local (`AC…` Account SID). Outbound sends still
    worked from both, but inbound webhook signatures — which Twilio ALWAYS
    signs with the Account Auth Token — were rejected with 403 on Railway,
    producing Twilio error 12300 on every inbound WhatsApp message.
  - This script verifies the local credentials against the Twilio API and
    prints a paste-ready block for Railway Variables.

Run:
    python scripts/gen_railway_twilio_env.py

⚠️  The output contains SECRETS (TWILIO_AUTH_TOKEN) — treat it like your .env.
"""
import datetime
import os
from dotenv import load_dotenv

load_dotenv()

KEYS = [
    "TWILIO_ACCOUNT_SID",
    "TWILIO_AUTH_TOKEN",
    "TWILIO_FROM_PHONE",
    "TWILIO_CONTENT_SID",
    "USE_TWILIO",
    "USE_WHATSAPP",
    "USE_ROUTINE_UPDATES",
]

sid = os.environ.get("TWILIO_ACCOUNT_SID", "").strip()
token = os.environ.get("TWILIO_AUTH_TOKEN", "").strip()

print("=== Verifying local Twilio credentials against the API ===")
if not sid or not token:
    print("ERROR: TWILIO_ACCOUNT_SID / TWILIO_AUTH_TOKEN missing from .env — nothing to generate.")
    raise SystemExit(1)

if sid.startswith("SK"):
    print("⚠️  TWILIO_ACCOUNT_SID is an SK… API Key SID.")
    print("    Outbound sends will work, but inbound webhook signatures will ALWAYS fail (403 →")
    print("    Twilio error 12300) because Twilio signs webhooks with the Account Auth Token.")
    print("    Replace it with the AC… Account SID + matching Account Auth Token from")
    print("    Console → Account → API keys & live credentials.")
elif not sid.startswith("AC"):
    print(f"⚠️  TWILIO_ACCOUNT_SID does not start with AC… (unusual format: {sid[:2]}…).")

try:
    from twilio.rest import Client
    acct = Client(sid, token).api.accounts(sid).fetch()
    print(f"✅ Credentials valid — account: {acct.friendly_name!r} (type: {acct.type})")
except Exception as exc:
    print(f"❌ Credentials FAILED validation: {exc}")
    print("   Fix .env before generating the Railway block.")
    raise SystemExit(1)

content_sid = os.environ.get("TWILIO_CONTENT_SID", "").strip()
if not content_sid:
    print("⚠️  TWILIO_CONTENT_SID is UNSET — standalone WhatsApp sends will fail with error 21654")
    print("    unless the recipient messaged the number within the last 24h. Create an approved")
    print("    WhatsApp Content Template (Console → Messaging → Content Editor) with a {{1}}")
    print("    variable, then set its SID here and in Railway.")

print("\n=== Paste this into Railway (Variables), then redeploy ===")
from_phone = os.environ.get("TWILIO_FROM_PHONE", "").strip() or "+14155238886"
print(f"# Twilio — canonical account (owns the WhatsApp number {from_phone})")
print(f"# generated by {os.path.basename(__file__)} on {datetime.date.today()}")
for k in KEYS:
    v = os.environ.get(k, "").strip()
    if k == "TWILIO_FROM_PHONE" and not v:
        v = "+14155238886"  # Twilio sandbox fallback used by the app
    print(f"{k}={v}")
print()
print("# After redeploying, re-run scratch/diag_webhook.py — it should return")
print("# HTTP 200 with a <Response> TwiML body instead of 403, and Twilio logs")
print("# should stop showing error 12300 on inbound messages.")
